<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Exam Completion Report - {{ $exam->title }}</title>
    <style>
        body { font-family: 'Helvetica', sans-serif; color: #333; padding: 20px; }
        .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 20px; margin-bottom: 30px; }
        .title { font-size: 22px; font-weight: bold; margin: 0; }
        .subtitle { font-size: 14px; color: #666; margin-top: 5px; }
        .stats-grid { width: 100%; margin-bottom: 30px; }
        .stat-box { background: #f9f9f9; padding: 15px; border: 1px solid #ddd; text-align: center; }
        .stat-label { font-size: 10px; text-transform: uppercase; color: #777; margin-bottom: 5px; }
        .stat-value { font-size: 18px; font-weight: bold; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #f2f2f2; font-size: 11px; text-align: left; padding: 10px; border: 1px solid #ddd; }
        td { padding: 10px; border: 1px solid #ddd; font-size: 10px; }
        .status-badge { padding: 3px 8px; border-radius: 4px; font-weight: bold; font-size: 9px; }
        .status-eligible { background: #e6fffa; color: #2c7a7b; }
        .status-blocked { background: #fff5f5; color: #c53030; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: center; font-size: 9px; color: #999; border-top: 1px solid #eee; padding-top: 10px; }
    </style>
</head>
<body>
    <div class="header">
        <div class="title">Global International School</div>
        <div class="subtitle">Official Examination Participation Audit Log</div>
    </div>

    <table style="width: 100%; margin-bottom: 30px;">
        <tr>
            <td style="border: none; padding: 0; width: 60%;">
                <div style="font-size: 16px; font-weight: bold;">{{ $exam->title }}</div>
                <div style="font-size: 11px; color: #666;">Subject: {{ $exam->subject->name }} | Class: {{ $exam->class->name }}</div>
                <div style="font-size: 11px; color: #666;">Date: {{ $exam->exam_date }} | Timing: {{ $exam->start_time }} - {{ $exam->end_time }}</div>
            </td>
            <td style="border: none; padding: 0; width: 40%; text-align: right; vertical-align: top;">
                <div style="font-size: 10px; color: #999;">REFERENCE ID: #EXAM-{{ $exam->id }}</div>
            </td>
        </tr>
    </table>

    <table class="stats-grid">
        <tr>
            <td class="stat-box">
                <div class="stat-label">Total Participation</div>
                <div class="stat-value">{{ $exam->eligibilityChecks->count() }}</div>
            </td>
            <td class="stat-box">
                <div class="stat-label">Approved Students</div>
                <div class="stat-value">{{ $exam->eligibilityChecks->where('is_eligible', true)->count() }}</div>
            </td>
            <td class="stat-box">
                <div class="stat-label">Disqualified Cases</div>
                <div class="stat-value">{{ $exam->eligibilityChecks->where('is_eligible', false)->count() }}</div>
            </td>
        </tr>
    </table>

    <table>
        <thead>
            <tr>
                <th>Sr.</th>
                <th>Admission No</th>
                <th>Student Name</th>
                <th>Attendance %</th>
                <th>Audit Status</th>
                <th>Override Reason</th>
            </tr>
        </thead>
        <tbody>
            @foreach($exam->eligibilityChecks as $index => $audit)
            <tr>
                <td>{{ $index + 1 }}</td>
                <td style="font-weight: bold;">{{ $audit->student->admission_number }}</td>
                <td>{{ $audit->student->user->name }}</td>
                <td>{{ $audit->attendance_percentage }}%</td>
                <td>
                    <span class="status-badge {{ $audit->is_eligible ? 'status-eligible' : 'status-blocked' }}">
                        {{ $audit->is_eligible ? 'APPROVED' : 'BLOCKED' }}
                    </span>
                </td>
                <td style="color: #888;">{{ $audit->reason ?: 'N/A' }}</td>
            </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by Exam Management System Intelligence Hub | Date: {{ now()->format('M d, Y h:i A') }}
    </div>
</body>
</html>
